### ISSUE TITLE
auv_msgs ROS release 

### ISSUE THREAD

**Issue by bmagyar** [oceansystemslab/auv_msgs#1]
Hello everyone!

We at the Ocean Systems Lab at Heriot-Watt University thought it is time to give a proper release to this package that first originated from our lab. Once we converge on a version that satisfies most (or all) participants, the package will be released and will be _available to install via apt-get starting from ROS Indigo_.

I had some interactions with most of you prior to this post to make sure I'm inviting the right people to the discussion.

If you don't want to receive emails of new posts on this issue, use the _Unsubscribe_ button in the _Notifications_ area on the right.

We have seen many different versions of auv_msgs floating around the internet and suspect that there are others inside different labs as well. 

I invite all of you to put your thoughts here, and perhaps a _list of messages, actions and services_ you'd ideally have in this package. Please provide links to these message definitions if they are different from the one currently in this repository.

Let's concentrate on the AUV scope now and the specialized sensors. Vectors, project-related and other utility messages should be excluded unless they are tightly associated with the AUV domain.

The next list of people include contributors/users from Heriot-Watt University, University of Zagreb, Universitat de Girona, Universitat Jaume I and Óbuda University.

@mvaldenegro @gatufella @decabyte  @henriqueribeiro @miguel-r @dulanad @narcispr @perezsolerj @marioprats @RandomKraken 

Feel free to add more people to the list as you see fit.

**Comment by narcispr** [comment]
Hi everyone, 
The current auv_msgs package covers all the necessities for UdG and our COLA2 architecture. However, in my opinion, there are lots of actions/messages/services in this package that are not AUV related or very specific to be in a _generic_ auv_msgs repository.

I can see almost three subgroups: Geometry related messages, Intervention mesages (few AUVs have a manipulator) and Vision-based messages. Moreover, there are several undefined messages and some other messages that are very specific just for a particular task or sensor. I don't know if it is a good idea to put all of them together. In general sensor_msgs, nav_msgs, geometry_msgs, ... have only **core** messages. I think we should do something similar here. 

I see at least these groups:

**Geometry related messages:**
- GenerateObjectModel.action
- Circles2D.msg
- Circles2DArray.msg
- PointArray.msg
- Pose2D.msg —> There is a geometry_msg with the same name. I suggest a rename.
- Sphere.msg
- SphereArray.msg

**Intervention messages:**
- ObjectOperation.action
- PerformInterventionStrategy.action
- InterventionSpec.msg
- InterventionStrategySpec.msg
- InterventionTaskSpec.msg
- SetInerventionConfig.srv

**Vision-based messages:**
- LocaliseInMosaic.action
- VideoSensinQuality.action
- ImageFeature.msg

**Undefined messages (they are empty):**
- CollectData.action
- EnterDock.action
- LeaveDock.action
- ObjectModel.msg

**Others:**
- Mcm_.action —> I don’t know if Mcm_ actions are very generic or if they are used only in very specific missions.
- SonarInspect.action & SonarObserve.action —> Can we put them a more general names like Inspect & Observe actions (the later already exists but has less params). I mean if we want to inspect with a camera why we need to use a Sonar inspect message?
- SonarCircles/Lines.msg —> Again, lines and circles can be detected in both vision or acoustic based images.
- AcousicModemData.msg —> Why MAX_PAYLOAD_SIZE is defined to 2048?
- Test.msg —> It contains only a float64 and the name is very confusing
- bvtSonarOutputParam.msg —> This message seems to be very custom for a particular sensor. I
- GenerateIPsFromOctomap.srv —> It seems a very specific service too.

**Core messages:**
- The rest :)

On the other hand, it could be a good idea to define some AUV _standard_ sensor msgs that are not provided by the package sensor_msgs. For instace:
- DVL
- USBL
- CTD
- Water velocity/depth/temperature
- ... 

What do you think?
Cheers!

**Comment by decabyte** [comment]
Hi Narcis,

+1 from me. I think your suggestion is spot on. Ambiguous stuff should be
removed as well as mission specific messages or actions. ;)

My two cents,
Valerio

**Comment by henriqueribeiro** [comment]
Hi guys,

To be honest, here at IST we don't use so much actions and services, so we
are not at ease to help to improve this.

On other hand, and relative to messages itself, we agree with everything
that Narcis said. But tell me something, it is possible to separate
"physically" the subgroups into the same package, or it is just at
conceptual level? Because I think that we should keep the package
user-friendly  and intuitive. So maybe we should do like other messages
libs (sensor_msgs, nav_msgs, etc) and create a metapackage and inside that
we have packages for all the subgroups that Narcis proposed.

Relative to the AUV _sensor_ msgs, should we try to do a push request to
the main sensor_msgs package repo? Or should we have one for just for "us"?
We also have some proposals for the sensors, but let's leave that for later.

Concerning the _Core_ messages we have only one change to propose (Dula
correct me if I'm wrong) on NavSts message:
- Replace the "global_position" and "origin" type by
  geographic_msgs/GeoPoint. This geographic message is already on the main
  ROS repo and it's identical to the DecimalLatLon (maybe remove the
  DecimallatLon?).
- On the _body velocities_ section we suggest a new field to represent
  the velocity over ground. So in this section, we have velocity over water
  and velocity over ground. This could be very useful for handle water
  currents.
- Last, on the _status and flags_ section we added some constants to
  take care this new fields.

Cheers,
Henrique

**Comment by decabyte** [comment]
Hi @henriqueribeiro,

these are good points.

> On other hand, and relative to messages itself, we agree with everything
> that Narcis said. But tell me something, it is possible to separate
> "physically" the subgroups into the same package, or it is just at
> conceptual level? Because I think that we should keep the package
> user-friendly and intuitive. So maybe we should do like other messages
> libs (sensor_msgs, nav_msgs, etc) and create a metapackage and inside that
> we have packages for all the subgroups that Narcis proposed.

@bmagyar @narcispr this should be possible isn't it? 

On the other hand can you provide a small example for these two:

> - On the _body velocities_ section we suggest a new field to represent
>   the velocity over ground. So in this section, we have velocity over water
>   and velocity over ground. This could be very useful for handle water
>   currents.
> - Last, on the _status and flags_ section we added some constants to
>   take care this new fields.

so everybody can be on the same page?

Cheers,
Valerio

**Comment by henriqueribeiro** [comment]
Sure! Below is the diff

NavSts.msg

> - DecimalLatLon global_position
> 
> ## \- DecimalLatLon origin
> - geographic_msgs/GeoPoint global_position
> - geographic_msgs/GeoPoint origin
- # Body velocities in metres/sec.
  
  > ## \- geometry_msgs/Point body_velocity
  > - # Body velocities relative to water in metres/sec.
  > - geometry_msgs/Point water_velocity
  > - # Body velocities relative to ground in metres/sec.
  > - geometry_msgs/Point ground_velocity
- uint8 STATUS_VELOCITY_OK = 4
  
  > ## \- uint8 STATUS_ALL_OK = 15
  > - uint8 STATUS_WATER_VELOCITY_OK = 16
  > - uint8 STATUS_GROUND_VELOCITY_OK = 32
  > - uint8 STATUS_VELOCITY_OK = 48
  > - uint8 STATUS_ALL_OK = 59

**Comment by bmagyar** [comment]
First of all, thanks for the feedback.

I would be very pedantic and throw everything out that is not closely tied to the AUV domain, this applies to vision, geometry, non-generic task-related and project leftover messages.
These could be moved to their specific application_, project_ or mylab_msgs packages of their users/owners.

The suggestion on sensor_msgs in the metapackage sounds good, but it wouldn't work. Even though ROS packages can be grouped via metapackages, but these don't form a namespace, so we'd had collisions with duplicated package names. 

While the current general packages seem to be packed with mostly ground robot-related or general messages, they are nicely categorized. The simplest way forward would be to skip this categorization, and pack everything that is unique to the AUV domain in auv_msgs. Sensor messages such as the DVL, USBL, CTD, Water velocity/depth/temperature and navigation related packages are good examples for this. 

We could have auv_core_msgs/auv_msgs, auv_sensor_msgs, auv_nav_msgs. Personally I'm not very settled on either side on this matter, I think it's best to delay this decision until we have the final list of messages we are happy with.

On the flip side, vision messages I think should be removed, as that is related to a camera that operates in a though environment, not to AUVs specifically. 

If we can converge on some solid concepts of the most common AUV-related interventions, simple and reusable action or message definitions could be added. Don't hold back your suggestions :)

**Comment by bmagyar** [comment]
Hello again,

I have made the first release of auv_msgs to Indigo today.

The fresh binaries will be available from the 1st of April. You can see the current state of the package on this repo. I made my best effort to comply with everyone, so we can start from a common ground breaking the least amount of code.

Give it a go and see if you have issues that cannot be solved easily and would require adding more messages.

I'm going to close this thread, since the release has happened. 
Feel free to put open new issues as you see fit.
