### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by russkel** [oceansystemslab/auv_msgs#5]
Hello,

Is there any interest in supporting ROS2 with this package?

Thanks.

**Comment by bmagyar** [comment]
I currently don't have a lot of bandwidth to support this package but if you are happy to port it, I'm happy to open a branch to open PR-s against and push a release to any ROS2 distro you desire.

**Comment by russkel** [comment]
@bmagyar No problem. I will raise a PR when I get the work done.

**Comment by bmagyar** [comment]
I've created `ros2-master` for you

**Comment by russkel** [comment]
Fixed in #6
